[package]
name = "alloy-transport-ws"
description = "Websocket transport implementation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--show-type-layout",
]

[lints]
workspace = true

[dependencies]
alloy-pubsub.workspace = true
alloy-transport.workspace = true

futures.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }
tracing.workspace = true

# non-WASM only
[target.'cfg(not(target_family = "wasm"))'.dependencies]
http = "1.1"
tokio = { workspace = true, features = ["sync", "rt", "time"] }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }

# WASM only
[target.'cfg(target_family = "wasm")'.dependencies]
ws_stream_wasm = "0.7.4"
