[package]
name = "alloy-serde"
description = "Alloy serde helpers"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
serde.workspace = true
serde_json = { workspace = true, features = ["alloc"] }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["rand", "rlp", "serde", "arbitrary"] }

[features]
default = ["std"]
std = ["alloy-primitives/std", "serde/std", "serde_json/std"]
