[package]
name = "alloy-rpc-types-eth"
description = "Types for the `eth` Ethereum JSON-RPC namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-network-primitives.workspace = true
alloy-rlp = { workspace = true, features = ["arrayvec", "derive"] }
alloy-primitives = { workspace = true, features = ["rlp", "map"] }

itertools.workspace = true
derive_more = { workspace = true, features = ["display"] }

# serde
alloy-serde = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }

# arbitrary
arbitrary = { version = "1.3", features = ["derive"], optional = true }

# jsonrpsee
jsonrpsee-types = { version = "0.24", optional = true }
alloy-sol-types.workspace = true

[dev-dependencies]
alloy-primitives = { workspace = true, features = [
    "rand",
    "rlp",
    "serde",
    "arbitrary",
] }
alloy-consensus = { workspace = true, features = ["std", "arbitrary"] }
alloy-eips = { workspace = true, features = ["arbitrary", "k256"] }

arbitrary = { workspace = true, features = ["derive"] }
rand.workspace = true
similar-asserts.workspace = true
assert_matches.workspace = true

[features]
default = ["std", "serde"]
std = ["alloy-primitives/std", "alloy-consensus/std", "alloy-eips/std"]
serde = [
    "dep:serde",
    "dep:serde_json",
    "dep:alloy-serde",
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
]
arbitrary = [
    "std",
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-serde?/arbitrary",
    "alloy-eips/arbitrary",
]
jsonrpsee-types = ["dep:jsonrpsee-types"]
k256 = ["alloy-consensus/k256", "alloy-eips/k256"]
