[package]
name = "alloy-rpc-types-eth"
description = "Types for the `eth` Ethereum JSON-RPC namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--show-type-layout",
]

[lints]
workspace = true

[dependencies]
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-consensus-any.workspace = true
alloy-network-primitives.workspace = true
alloy-rlp = { workspace = true, features = ["arrayvec", "derive"] }
alloy-primitives = { workspace = true, features = ["rlp", "map"] }
alloy-block-access-list.workspace = true
itertools.workspace = true
thiserror.workspace = true

# serde
alloy-serde = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_with = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

# arbitrary
arbitrary = { version = "1.3", features = ["derive"], optional = true }

# jsonrpsee
jsonrpsee-types = { workspace = true, optional = true }
alloy-sol-types.workspace = true

[dev-dependencies]
alloy-primitives = { workspace = true, features = [
	"rand",
	"rlp",
	"serde",
	"arbitrary",
] }
alloy-consensus = { workspace = true, features = ["std", "arbitrary"] }
alloy-eips = { workspace = true, features = ["arbitrary", "k256"] }

arbitrary = { workspace = true, features = ["derive"] }
rand.workspace = true
similar-asserts.workspace = true
assert_matches.workspace = true
bincode = { workspace = true, features = ["serde"] }

[features]
default = ["std", "serde"]
std = [
	"alloy-primitives/std",
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-consensus-any/std",
	"alloy-network-primitives/std",
	"alloy-serde?/std",
	"alloy-rlp/std",
	"alloy-sol-types/std",
	"serde?/std",
	"serde_json?/std",
	"thiserror/std",
	"serde_with?/std",
	"alloy-block-access-list/std"
]
serde = [
	"dep:serde",
	"dep:serde_json",
	"dep:alloy-serde",
	"alloy-primitives/serde",
	"alloy-consensus/serde",
	"alloy-eips/serde",
	"alloy-consensus-any/serde",
	"rand/serde",
	"alloy-network-primitives/serde",
]
arbitrary = [
	"std",
	"dep:arbitrary",
	"alloy-consensus/arbitrary",
	"alloy-primitives/arbitrary",
	"alloy-serde?/arbitrary",
	"alloy-eips/arbitrary",
	"alloy-consensus-any/arbitrary",
	"alloy-sol-types/arbitrary",
	"alloy-block-access-list/arbitrary"

]
jsonrpsee-types = ["dep:jsonrpsee-types"]
k256 = ["alloy-consensus/k256", "alloy-eips/k256"]
serde-bincode-compat = ["serde", "dep:serde_with", "alloy-eips/serde-bincode-compat"]
