[profile.default]
retries = { backoff = "exponential", count = 2, delay = "2s", jitter = true }
slow-timeout = { period = "30s", terminate-after = 4 }

[[profile.default.overrides]]
filter = "test(can_launch_reth_custom_ports)"
retries = { backoff = "exponential", count = 5, delay = "3s", jitter = true }
