[package]
name = "alloy-transport"
description = "Low-level Ethereum JSON-RPC transport abstraction"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--show-type-layout",
]

[lints]
workspace = true

[dependencies]
alloy-json-rpc.workspace = true

base64.workspace = true
futures-utils-wasm.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
serde.workspace = true
thiserror = { workspace = true, features = ["std"] }
tower.workspace = true
url.workspace = true
tracing.workspace = true
governor = { version = "0.10", default-features = false, features = [
    "std",
    "quanta",
], optional = true }
futures.workspace = true
parking_lot.workspace = true
derive_more.workspace = true
auto_impl.workspace = true

# Test-only dependencies
[dev-dependencies]
alloy-primitives.workspace = true

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
tokio = { workspace = true, features = ["rt", "time", "sync", "macros"] }

# wasm32-unknown-unknown (Browser)
[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
wasm-bindgen-futures = { version = "0.4", optional = true }
wasmtimer.workspace = true

[features]
wasm-bindgen = ["dep:wasm-bindgen-futures"]
throttle = ["dep:governor"]
